multiplication/urls.py
from django.urls import path
from . import views

app_name = "multiplication"
urlpatterns = [
    path('', views.index, name='index'),
    path('input/', views.index, name='input'),
    path('stat/', views.stat, name='stat'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('multiplication.urls')),
    path('admin/', admin.site.urls),
]

multiplication/models.py
from django.db import models

# Create your models here.
class Multiplication(models.Model):
    number = models.PositiveIntegerField()
    count = models.PositiveIntegerField(default=1)

multiplication/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Multiplication
# Create your views here.

def index(request):
    context = {}
    if "number" in request.GET:
        if request.GET['number'] != '':

            if not Multiplication.objects.filter(number=int(request.GET['number'])):
                obj = Multiplication(number=int(request.GET['number']))
                obj.save()
                context['count'] = Multiplication.objects.filter(number=int(request.GET['number'])).count
            else:
                obj = Multiplication.objects.get(number=int(request.GET['number']))
                obj.count += 1
                obj.save()
            context['multipliction_obj'] = obj
            result = [int(request.GET['number'])*i for i in range(1,13)]
            context['result'] = result
    return render(request, "multiplication/index.html",context)

def stat(request):
    context = {'stat_list': Multiplication.objects.all().order_by('number')}
    return render(request, "multiplication/statistics_multiplication.html",context)
    
    

multiplication/templates/multiplication/index.html
<!DOCTYPE html>
<html>
<head>
    <style>
    table, th, td { 
        text-align:center;
        border: 1px solid black;    
    }
    th, td { 
        padding : 5px;
    }
    </style>
</head>

<body>
<form action = "{%url 'multiplication:input' %}" method=get>
    Number :
    <input type='text' name=number>
    <input type='submit' value="Enter">
</form>
<br>
<form action = "{%url 'multiplication:stat' %}" method=get>
    <input type='submit' value="Statistics" >
</form>
{% if result %}
    <h1>Multiplication table of {{multipliction_obj.number}}</h1>
    <table >
        <tr>
            <th>Multiplication</th>
            <th>Result</th>
        </tr>
        {% for val in result%}
        <tr>
            <td>{{multipliction_obj.number}} X {{forloop.counter}}</td>
            <td>{{val}}</td>
        </tr>
        {% endfor %}
    </table>
    <p>Number times showing result : {{multipliction_obj.count}} time{{ multipliction_obj.count|pluralize }}</p>
{% endif %}
</body>

multiplication/templates/multiplication/statistics_multiplication.html
<!DOCTYPE html>
<html>
<head>
    <style>
    table, th, td { 
        text-align:center;
        border: 1px solid black;    
    }
    th, td { 
        padding : 5px;
    }
    </style>
</head>

<body>
<h1>Statistics of Number times showing multiplication</h1>
<table >
    <tr>
        <th>Number</th>
        <th>Number of times to showing</th>
    </tr>
    {% for obj in stat_list%}
    <tr>
        <td>{{obj.number}}</td>
        <td>{{obj.count}} time{{ obj.count|pluralize }}</td>
    </tr>
    {% endfor %}
</table>
<br>
<form action = "{%url 'multiplication:index' %}" method=get>
    <input type='submit' value="back">
</form>
</body>